// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD4MkJR5MrYshed8IeyvXmGatGnrHryCM',
    appId: '1:754093121913:web:407abdfc7d72a0f76e0fa8',
    messagingSenderId: '754093121913',
    projectId: 'reddit-clone-app-f325e',
    authDomain: 'reddit-clone-app-f325e.firebaseapp.com',
    storageBucket: 'reddit-clone-app-f325e.appspot.com',
    measurementId: 'G-RTWKJKSQNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHNZrHgRbjG8vSSF56gdxG-wYo5rP3bo',
    appId: '1:754093121913:android:22c92322f0fe0ef06e0fa8',
    messagingSenderId: '754093121913',
    projectId: 'reddit-clone-app-f325e',
    storageBucket: 'reddit-clone-app-f325e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkVNpSFj2C8X_QigE_c0OfQfJp5aNKTpc',
    appId: '1:754093121913:ios:42ab518886b671b86e0fa8',
    messagingSenderId: '754093121913',
    projectId: 'reddit-clone-app-f325e',
    storageBucket: 'reddit-clone-app-f325e.appspot.com',
    iosClientId: '754093121913-q7gmv70tjpnnknrqoarrcr6o60mitolr.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
